### ISSUE TITLE
How to replicate this project

### ISSUE THREAD

**Issue by Harry97** [lunatolun/meteor-vue-vuerouter-vuex#1]
It'd be nice to write a step by step guide on how to create/replicate this project on one's own device just like Akryum did [here](https://github.com/Akryum/meteor-vue2-example), so that we can how know what packages are imported and how they were imported, and also be able to create our own in case you forgot to update this repo. Thanks!

**Comment by Harry97** [comment]
The reason I'm interested in how to replicate it is because there're so many ways to import packages and even different packages are imported across guides. I tried to create a project that integrates vue, vue-router, vuex and meteor all together using these guide down below, and as you can tell by this issue, things got mixed up pretty quickly.
https://github.com/Akryum/meteor-vuex-example
https://github.com/Akryum/meteor-vue2-example
https://github.com/Akryum/meteor-vue2-example-routing
https://forums.meteor.com/t/basics-setting-up-a-meteor-vuejs-project/32832/59 (This is where I found out about yours)

**Comment by lunatolun** [comment]
This doesn't have complicated stuff. Just clone it and do 
`meteor npm install && meteor`
If you compare 'meteor/packages' and packages.json to those repositories you will understand the difference. Unfortunately I don't have time to write detailed documentation at the moment and its not really necessary since everything you see are from either NPM or Meteor packages. You can check the docs from Vue/Vuex docs or used packages' docs.

**Comment by Harry97** [comment]
You're right, I apologize, I should've simply read the package.json file, and figured out what packages were used and what not. Sorry!
I cloned it and ran the command as you said, but I got a couple of errors. I had to run `meteor upgrade`, install babel-runtime, core-js, and to also run `meteor npm install --save vue vue-router vuex vue-meteor-tracker` as there was some issue with modules. Finally, when it worked, I got this error in my console saying `Uncaught Error: Cannot find module 'buffer'`.
